name: onoy_kg
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: 0.24.1
  get_it: ^5.0.3
  rx_command: ^5.2.1
  rx_widgets: ^3.1.0
  pedantic: ^1.9.2
  flutter_svg: ^0.22.0
  http: ^0.13.1
  email_validator: ^1.0.6
  logger: ^0.9.4
  toggle_switch: ^0.1.8
  intl: ^0.17.0
  recase: ^3.0.1
  strings: ^0.1.4
  firebase_core: ^1.0.0
  firebase_auth: ^1.1.3
  firebase_crashlytics: ^2.0.2
  pinput: ^1.0.0
  equatable: ^2.0.0
  buttons_tabbar: ^1.1.2
  image_picker: ^0.7.1
  shared_preferences: 2.0.5
  flutter_native_image: ^0.0.5
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.0
dev_dependencies:
  effective_dart: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
        - asset: fonts/Gilroy-Heavy.ttf
        - asset: fonts/Gilroy-Light.ttf
        - asset: fonts/Gilroy-Medium.ttf
        - asset: fonts/Gilroy-Regular.ttf
